[workspace]
members = ["operators"]
resolver = "3"
package.edition = "2024"

[workspace.dependencies]
clrt.path = "../clrt/clrt"
search-cl-tools.path = "../clrt/search-cl-tools"

infini-rt = { path = "../infini-toolkit/infini-rt" }
infini-op = { path = "../infini-toolkit/infini-op" }
infini-ccl = { path = "../infini-toolkit/infini-ccl" }
search-infini-tools = { path = "../infini-toolkit/search-infini-tools" }

cuda = { path = "../cuda-driver/cuda" }
cublas = { path = "../cuda-driver/cublas" }
nccl = { path = "../cuda-driver/nccl" }
search-cuda-tools = { path = "../cuda-driver/search-cuda-tools" }
search-corex-tools = { path = "../cuda-driver/search-corex-tools" }
